### PR TITLE
Pop surfaces nicely

### LINKED ISSUE #518: popping surface with ents on it produces wrong order
1. Place display on surface
2. Pop surface

Expected: display + surface ejected, with display further out.
Actual: surface is further out

### PR DESCRIPTION
**Pull request by RobotCaleb**
Closes #518 

This doesn't touch the surf kind mesh stuff. Overall it's much better, though.

### CODE REVIEW

File: main.cc [hunk 1]
```diff
@@ -301,7 +301,10 @@ init()
     frame_index = 0;
 
     pl.rot = glm::quat(1, 0, 0, 0);
+    auto m = glm::mat4_cast(glm::normalize(pl.rot));
```
Comment (chrisforbes) [inline main.cc:304]: We saw all kinds of bad behavior in initial bullet state already -- is this why?
